"""empty message

Revision ID: 0b749f51ca3b
Revises: f07212c7c813
Create Date: 2019-04-20 10:12:33.394927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b749f51ca3b'
down_revision = 'f07212c7c813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'articles', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'author_id')
    # ### end Alembic commands ###
